trying a modification ease change

diff --git a/mpp-solar-setup b/mpp-solar-setup
--- a/mpp-solar-setup
+++ b/mpp-solar-setup
@@ -1,5 +1,26 @@
 #!/bin/bash
 
+echo "Remember to modify this script to use your current MQTT connection details and the correct /dev/hidraw# numbers."
+read -n1 -r -p "Do you want to continue? (Y/N) [Default: No]: "
+
+if [[ $REPLY =~ ^[Yy]$ ]]; then
+  # User chose Y, so execute the rest of the script
+  echo "Continuing..."
+else
+  # User chose N or didn't respond, so exit the script
+  echo "Aborted."
+  exit 1
+fi
+
+# MODIFY THESE LINES
+mqttBroker=192.168.0.100
+mqttUser=user
+mqttPass=pass
+inverter1Port=/dev/hidraw1
+inverter2port=/dev/hidraw2
+# DO NOT MODIFY BELOW THIS LINE
+
+
 sudo usermod -a -G plugdev $USER
 
 sudo sh -c 'cat <<\EOF >/etc/udev/rules.d/99-hidraw.rules
@@ -24,15 +45,15 @@ sudo sh -c 'cat <<\EOF >/etc/mpp-solar/mpp-solar.conf
 # Number of seconds to pause between command execution loop
 # 0 is no pause, greater than 60 will cause service restarts
 pause=5
-mqtt_broker=192.168.0.100
-mqtt_user=user
-mqtt_pass=pass
+mqtt_broker=${mqttBroker}
+mqtt_user=${mqttUser}
+mqtt_pass=${mqttPass}
 
 
 # This example would work on a single LV5048
 [Inverter1_LV5048]
 protocol=PI41
-port=/dev/hidraw1
+port=${inverter1Port}
 baud=2400
 command=QPGS0
 tag=LV5048
@@ -40,7 +61,7 @@ outputs=hass_mqtt
 
 [Inverter2_LV5048]
 protocol=PI41
-port=/dev/hidraw1
+port=${inverter1Port}
 baud=2400
 command=QP2GS0
 tag=LV5048
@@ -48,7 +69,7 @@ outputs=hass_mqtt
 
 [Inverter3_LV6048]
 protocol=PI41
-port=/dev/hidraw2
+port=${inverter2port}
 baud=2400
 command=QPGS0
 tag=LV6048
@@ -57,7 +78,7 @@ outputs=hass_mqtt
 
 [Inverter4_LV6048]
 protocol=PI41
-port=/dev/hidraw2
+port=${inverter2port}
 baud=2400
 command=QP2GS0
 tag=LV6048
